apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailnotificationservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailnotificationservice
  template:
    metadata:
      labels:
        app: emailnotificationservice
    spec:
      containers:
      - name: emailnotificationservice
        image: msaregistry.azurecr.io/emailnotificationservice:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: emailnotificationservice-service
spec:
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: emailnotificationservice