apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbdataloggingservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodbdataloggingservice
  template:
    metadata:
      labels:
        app: mongodbdataloggingservice
    spec:
      containers:
      - name: mongodbdataloggingservice
        image: msaregistry.azurecr.io/mongodbdataloggingservice:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbdataloggingservice-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mongodbdataloggingservice
